# Generated by Django 6.0.5 on 2026-06-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_service_booking_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
