# Generated by Django 6.0.5 on 2026-06-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_service_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='service',
            new_name='services',
        ),
    ]
